apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rcp7ue830-go 
  janus-idp.io/tekton: rcp7ue830-go
  backstage.io/kubernetes-id: rcp7ue830-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rcp7ue830-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml