apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rcp7ue830-go-gitops
  description: This is GitOps manifest for rcp7ue830-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=rcp7ue830-go
    backstage.io/kubernetes-id: rcp7ue830-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: rcp7ue830-go-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rcp7ue830-go
