apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rcp7ue830-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rcp7ue830-go 
  name: rcp7ue830-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rcp7ue830-go 
